language: java

jdk:
  - openjdk11

branches:
  only:
    - master
    - dev

cache:
  directories:
    - $HOME/.m2

# Overrides travis 'install' step.
# This installs dependencies using default profile.
install:
  - java -version
  - mvn --version
  - sudo /usr/local/maven/bin/mvn --batch-mode clean compile -DskipTests=true -Dmaven.buildNumber.skip=true

# overrides travis 'script' step
script:
  - sudo /usr/local/maven/bin/mvn --batch-mode clean package -Dmaven.buildNumber.skip=true

after_success:
  # using environment variable $repo_token set in travis web site
  - sudo /usr/local/maven/bin/mvn clean test cobertura:cobertura coveralls:report -DrepoToken=$repo_token -Dmaven.buildNumber.skip=true
  
notifications:
  email:
    on_success: never
    on_failure: always