buildInfo: "${buildRevision} ${scmBranch} Build at ${buildDateTime}"
profile: ${profile}

importantProperty1: ${importantProperty1}
importantProperty2: ${importantProperty2}
maxAllowedResults: ${maxAllowedResults}

server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: ${http.port}

logging:
  level: INFO
  appenders:
    - type: file
      threshold: ALL
      timeZone: GMT-3
      currentLogFilename: ./logs/menuapp_dw.log
      archivedLogFilenamePattern: ./logs/menuapp_dw-%d.log.gz
      archivedFileCount: 5
    - type: console
      threshold: ALL
      timeZone: GMT-3
  loggers:
    org.fabri1983.menuapp: INFO
