buildInfoConfig:
  buildInfo: "${buildRevision} ${scmBranch}. Build at ${buildDateTime}"
  buildProfile: ${buildProfile}

menuQueryConfig:
  defaultCurrency: ${defaultCurrency}
  pageLimit: ${pageLimit}
  maxAllowedResults: ${maxAllowedResults}

server:
  type: default
  applicationContextPath: /
  adminContextPath: /admin
  applicationConnectors:
    - type: http
      port: ${http.port}
#    - type: https
#      port: 8443
#      keyStorePath: example.keystore
#      keyStorePassword: example
#      validateCerts: false
#      validatePeers: false
  adminConnectors:
    - type: http
      port: 8081
#    - type: https
#      port: 8444
#      keyStorePath: example.keystore
#      keyStorePassword: example
#      validateCerts: false
#      validatePeers: false

couchbaseClientFactory:
  bucket: default
  hosts:
    - http://localhost:8091/pools
  password: ""

logging:
  level: INFO
  appenders:
    - type: file
      threshold: ALL
      timeZone: GMT-3
      currentLogFilename: ./logs/menuapp_dw.log
      archivedLogFilenamePattern: ./logs/menuapp_dw-%d-%i.log.gz
      archivedFileCount: 5
      maxFileSize: 1MB
    - type: console
      threshold: ALL
      timeZone: GMT-3
      target: stdout
  loggers:
    org.fabri1983.menuapp: INFO
